import { Inter } from 'next/font/google'
import './globals.css'
import { Cart1 } from '@/widgets/component'
import logo1 from '../images/Group 188.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className={inter.className}>
      <header className='lg:w-[90%] m-auto'>
        <h1 className="text-[40px] font-mono font-bold">
          HISSOR <span className="text-[#159EEC]">CLINIK</span>
        </h1>
        <aside>
        <Cart1 img={logo1} name="Emergency" des="(237) 681-812-255"/>
        </aside>
      </header>
      <main>{children}</main>
    </div>
  )
}
