

// import { Inter } from 'next/font/google';
// import './globals.css';
// import { Cart1 } from '@/widgets/component';
// import logo1 from '../images/Group 188.png';
// import logo2 from '../images/Group 177.png';
// import logo3 from '../images/Group 178.png';
// import Link from 'next/link';
// import { Providers } from './provider';
// // import { Providers } from '@/store/Providers'; // подключаем наш клиентский wrapper

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <header className='lg:w-[90%] m-auto flex justify-between lg:p-[20px]'>
//           <h1 className="text-[40px] font-mono font-bold">
//             HISSOR <span className="text-[#159EEC]">CLINIK</span>
//           </h1>
//           <aside className='flex gap-[20px]'>
//             <Cart1 img={logo1} name="Emergency" des="(237) 681-812-255" />
//             <Cart1 img={logo2} name="Work Hour" des="09:00 - 20:00 Everyday" />
//             <Cart1 img={logo3} name="Location" des="Hissor City " />
//           </aside>
//         </header>

//         <div className='bg-[#159EEC] p-[20px]'>
//           <div className='flex text-white gap-[20px] lg:px-[70px]'>
//             <Link href='/'><h1>Home</h1></Link>
//             <Link href='/myPatient'><h1>MyPatient</h1></Link>
//             <Link href='/login'><h1>Login</h1></Link>
//           </div>
//         </div>

//         {/* Оборачиваем всё приложение в Providers */}
//         <Providers>
//           <main>{children}</main>
//         </Providers>
//       </body>
//     </html>
//   );
// }



// "use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { Cart1 } from "@/widgets/component";
import logo1 from "../images/Group 188.png";
import logo2 from "../images/Group 177.png";
import logo3 from "../images/Group 178.png";
import Link from "next/link";
import { Providers } from "./provider"; // твой wrapper для Redux, Theme и т.д.

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "HISSOR Clinic",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        {/* Header */}
        <header className="lg:w-[90%] m-auto flex flex-col lg:flex-row justify-between items-center lg:p-[20px] gap-4">
          <h1 className="text-[40px] font-mono font-bold">
            HISSOR <span className="text-[#159EEC]">CLINIK</span>
          </h1>
          <aside className="flex flex-col lg:flex-row gap-[20px]">
            <Cart1 img={logo1} name="Emergency" des="(237) 681-812-255" alt="Emergency Icon" />
            <Cart1 img={logo2} name="Work Hour" des="09:00 - 20:00 Everyday" alt="Work Hour Icon" />
            <Cart1 img={logo3} name="Location" des="Hissor City" alt="Location Icon" />
          </aside>
        </header>

   

        {/* Main content wrapped in Providers */}
        <Providers>
          <main className="lg:w-[90%] m-auto mt-6">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
