

import { Inter } from "next/font/google";
import "./globals.css";
import { Cart1 } from "@/widgets/component";
import logo1 from "../images/Group 188.png";
import logo2 from "../images/Group 177.png";
import logo3 from "../images/Group 178.png";
import { Providers } from "./provider"; 

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "HISSOR Clinic",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        {/* Header */}
        <header className="lg:w-[90%] m-auto flex flex-col lg:flex-row justify-between items-center lg:p-[20px] gap-4">
          <h1 className="text-[40px] font-mono font-bold">
            HISOR <span className="text-[#159EEC]">CLINIC</span>
          </h1>
          <aside className="hidden lg:flex  gap-[20px]">
            <Cart1 img={logo1} name="Emergency" des="(237) 681-812-255" alt="Emergency Icon" />
            <Cart1 img={logo2} name="Work Hour" des="09:00 - 20:00 Everyday" alt="Work Hour Icon" />
            <Cart1 img={logo3} name="Location" des="Hissor City" alt="Location Icon" />
          </aside>
        </header>

   

        {/* Main content wrapped in Providers */}
        <Providers>
          <main className="">{children}</main>
        </Providers>
       
      </body>
    </html>
  );
}
